name: Flutter_routs_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cupertino_date_picker: ^1.0.26+2
  date_format: ^1.0.8
  cupertino_icons: ^0.1.3
  flutter_swiper: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

